/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: c25f034b1787a223f5effc88017743ef)
interface __BaseEnv_CloudflareBindings {
	MEDIA: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	MEDIA_BASE: "https://media.cafa-studio.com";
	MEDIA_TRANSFORM: "off";
	PRODUCTION_URL: "https://cafa-studio.com";
	ADMIN_USERNAME: string;
	ADMIN_PASSWORD_HASH: string;
	SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MEDIA_BASE" | "MEDIA_TRANSFORM" | "PRODUCTION_URL" | "ADMIN_USERNAME" | "ADMIN_PASSWORD_HASH" | "SESSION_SECRET">> {}
}
